os: osx
dist: xenial
language: shell
before_install:
        - choco install python
        - python -m pip install --upgrade pip
      env: PATH=/c/Python37:/c/Python37/Scripts:$PATH
script: python3 unittesting.py

